import { LinkedInContact, SearchQuery } from "@/types/contact";

export const mockContacts: LinkedInContact[] = [
  {
    id: "1",
    fullName: "Ana Silva Santos",
    firstName: "Ana",
    lastName: "Silva Santos",
    headline: "Head of Engineering at TechCorp Brasil",
    profileUrl: "https://linkedin.com/in/anasilva",
    email: "ana.silva@techcorp.com.br",
    company: "TechCorp Brasil",
    position: "Head of Engineering",
    location: "São Paulo, Brasil",
    connectionDegree: "2nd",
    createdAt: new Date(),
  },
  {
    id: "2",
    fullName: "Carlos Eduardo Mendes",
    firstName: "Carlos Eduardo",
    lastName: "Mendes",
    headline: "Senior Software Developer | React | Node.js",
    profileUrl: "https://linkedin.com/in/carlosmendes",
    email: "carlos.mendes@gmail.com",
    phone: "+55 11 99999-0001",
    company: "StartupXYZ",
    position: "Senior Software Developer",
    location: "Rio de Janeiro, Brasil",
    connectionDegree: "3rd",
    createdAt: new Date(),
  },
  {
    id: "3",
    fullName: "Maria Fernanda Costa",
    firstName: "Maria Fernanda",
    lastName: "Costa",
    headline: "Product Manager | Agile | Digital Transformation",
    profileUrl: "https://linkedin.com/in/mariafcosta",
    company: "Banco Digital",
    position: "Product Manager",
    location: "Belo Horizonte, Brasil",
    connectionDegree: "2nd",
    createdAt: new Date(),
  },
  {
    id: "4",
    fullName: "Pedro Augusto Lima",
    firstName: "Pedro Augusto",
    lastName: "Lima",
    headline: "CTO & Co-founder at InnovateTech",
    profileUrl: "https://linkedin.com/in/pedrolima",
    email: "pedro@innovatetech.io",
    phone: "+55 21 98888-1234",
    company: "InnovateTech",
    position: "CTO & Co-founder",
    location: "Florianópolis, Brasil",
    connectionDegree: "1st",
    createdAt: new Date(),
  },
  {
    id: "5",
    fullName: "Juliana Rocha Ferreira",
    firstName: "Juliana",
    lastName: "Rocha Ferreira",
    headline: "Data Scientist | Machine Learning | Python",
    profileUrl: "https://linkedin.com/in/julianarocha",
    email: "juliana.rf@datacompany.com",
    company: "DataCompany",
    position: "Senior Data Scientist",
    location: "Curitiba, Brasil",
    connectionDegree: "2nd",
    createdAt: new Date(),
  },
];

export const mockSearchHistory: SearchQuery[] = [
  {
    id: "search-1",
    query: "Software Engineers São Paulo",
    filters: {
      keywords: "software engineer",
      location: "São Paulo",
      limit: 50,
    },
    resultsCount: 47,
    createdAt: new Date(Date.now() - 86400000),
    contacts: mockContacts.slice(0, 3),
  },
  {
    id: "search-2",
    query: "Product Managers Tech",
    filters: {
      keywords: "product manager",
      industry: "Technology",
      limit: 25,
    },
    resultsCount: 23,
    createdAt: new Date(Date.now() - 172800000),
    contacts: mockContacts.slice(2, 4),
  },
  {
    id: "search-3",
    query: "CTOs Startups Brasil",
    filters: {
      title: "CTO",
      keywords: "startup",
      location: "Brasil",
      limit: 30,
    },
    resultsCount: 18,
    createdAt: new Date(Date.now() - 259200000),
    contacts: mockContacts.slice(3, 5),
  },
];
