import { LinkedInContact, SearchQuery } from "@/types/contact";

export const mockContacts: LinkedInContact[] = [
  {
    id: "1",
    firstName: "João",
    lastName: "Silva",
    fullName: "João Silva",
    jobTitle: "Senior Software Engineer",
    headline: "Building scalable solutions at tech companies",
    seniorityLevel: "Senior",
    functionalLevel: "Engineering",
    email: "joao.silva@techcorp.com",
    linkedin: "https://linkedin.com/in/joaosilva",
    city: "São Paulo",
    state: "SP",
    country: "Brazil",
    companyName: "TechCorp Brasil",
    companyDomain: "techcorp.com",
    companyWebsite: "https://techcorp.com",
    companySize: "201-500",
    industry: "Technology",
    companyAnnualRevenue: "$50M",
    createdAt: new Date(),
  },
  {
    id: "2",
    firstName: "Maria",
    lastName: "Santos",
    fullName: "Maria Santos",
    jobTitle: "Head of Marketing",
    headline: "Driving growth through innovative marketing strategies",
    seniorityLevel: "Head",
    functionalLevel: "Marketing",
    email: "maria.santos@startup.io",
    mobileNumber: "+55 11 99999-9999",
    linkedin: "https://linkedin.com/in/mariasantos",
    city: "Rio de Janeiro",
    state: "RJ",
    country: "Brazil",
    companyName: "Startup.io",
    companyDomain: "startup.io",
    companyWebsite: "https://startup.io",
    companySize: "51-100",
    industry: "SaaS",
    companyTotalFunding: "$10M",
    createdAt: new Date(),
  },
  {
    id: "3",
    firstName: "Carlos",
    lastName: "Oliveira",
    fullName: "Carlos Oliveira",
    jobTitle: "CTO",
    headline: "Transforming businesses through technology",
    seniorityLevel: "C-Level",
    functionalLevel: "Engineering",
    email: "carlos@enterprise.com.br",
    linkedin: "https://linkedin.com/in/carlosoliveira",
    city: "Belo Horizonte",
    state: "MG",
    country: "Brazil",
    companyName: "Enterprise Solutions",
    companyDomain: "enterprise.com.br",
    companyWebsite: "https://enterprise.com.br",
    companySize: "501-1000",
    industry: "Information Technology",
    companyAnnualRevenue: "$100M",
    createdAt: new Date(),
  },
];

export const mockSearchHistory: SearchQuery[] = [
  {
    id: "search-1",
    query: "Software Engineers Brazil",
    filters: {
      contactJobTitle: ["Software Engineer"],
      contactLocation: ["Brazil"],
      emailStatus: ["validated"],
      fetchCount: 50,
    },
    resultsCount: 47,
    createdAt: new Date(Date.now() - 86400000),
    contacts: mockContacts,
  },
  {
    id: "search-2",
    query: "Marketing Leaders SaaS",
    filters: {
      contactJobTitle: ["Head of Marketing", "VP Marketing", "CMO"],
      companyIndustry: ["SaaS"],
      seniorityLevel: ["Head", "VP", "C-Level"],
      emailStatus: ["validated"],
      fetchCount: 100,
    },
    resultsCount: 89,
    createdAt: new Date(Date.now() - 172800000),
    contacts: mockContacts.slice(0, 2),
  },
];
