project_id = "rhczgphrswnlsknosudh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"

[functions.search-leads]
verify_jwt = false

[functions.fetch-dataset]
verify_jwt = false

[functions.suggest-jobs]
verify_jwt = false

[functions.import-to-base]
verify_jwt = false

[functions.send-campaign-emails]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.validate-emails]
verify_jwt = false

[functions.sync-crm-history]
verify_jwt = false

[functions.sync-email-status]
verify_jwt = false
