-- Add tracking columns to email_sends table
ALTER TABLE public.email_sends 
  ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS opened_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS opened_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS clicked_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS clicked_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS clicked_links JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS bounced_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS bounce_type TEXT,
  ADD COLUMN IF NOT EXISTS bounce_message TEXT,
  ADD COLUMN IF NOT EXISTS complained_at TIMESTAMP WITH TIME ZONE;